name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Inject Firebase Config into firebaseConfig.js (directly in the root)
      - name: Inject Firebase Config
        run: |
          echo "const firebaseConfig = {" > firebaseConfig.js
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> firebaseConfig.js
          echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> firebaseConfig.js
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> firebaseConfig.js
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> firebaseConfig.js
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> firebaseConfig.js
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'" >> firebaseConfig.js
          echo "};" >> firebaseConfig.js

      # Step 3: No deployment to a separate branch, since you are deploying from `main`
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  
